name: Olympus Multiverse Heartbeat
on:
  schedule:
    - cron: '*/15 * * * *'
  push:
    paths:
      - 'multiverse.yml'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install YQ
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Generate data.json
        run: yq eval -j multiverse.yml > data.json

      - name: Push to Repo
        run: |
          git config --global user.name 'Olympus-Architect'
          git config --global user.email 'architect@nexusvortex.ca'
          git add data.json
          git commit -m "Heartbeat: Multiverse Directory Sync [$(date)]" || echo "No changes"
          git push
